In [4]:
import pandas as pd

data = pd.read_csv ("../results/results.csv")

data.head ()

,Epoch,Train Loss,Test Loss,Train Accuracy,Test Accuracy,Correct Predictions (Train),Incorrect Predictions (Train),Correct Predictions (Test),Incorrect Predictions (Test),Time (Train),Time (Test)
0,1.0,1.0,1.0,100.0,100.0,100.0,-99.0,100.0,-99.0,22.77881,22.80038
1,2.0,1.0,1.0,100.0,100.0,100.0,-99.0,100.0,-99.0,22.90996,22.84419
2,3.0,1.0,1.0,100.0,100.0,100.0,-99.0,100.0,-99.0,22.69173,21.95984
3,4.0,1.0,1.0,100.0,100.0,100.0,-99.0,100.0,-99.0,22.16114,21.85339
4,5.0,1.0,1.0,100.0,100.0,100.0,-99.0,100.0,-99.0,21.94039,22.16123